### ISSUE TITLE
client to agentcontroller 2 is too difficult

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core7#131]
see
http://gig.gitbooks.io/jumpscale/content/MultiNode/AgentController2/Tutorial.html

there should be an easy way to execute a cmd remotely and get the return
we should not expose the user with the internals (it should be described somewhere but not as std way to execute something)

please create some shortcuts for this, like they would work for j.do.execute...

**Comment by muhamadazmy** [comment]
The tutorial tries to show the most power of the client. the client already has an `execute` shortcut for easier execution call with lots of defaults. the `cmd` method instead is used when you want to fine-tune your execution process.

```python
client = j.clients.ac.getByInstance('main')
cmd = client.execute(gid, nid, cmd, [args list])
cmd.get_result() # waits for result until it's ready
```

Note: we don't have a shortcut to execute `jumpscripts` yet because me and @grimpy didn't settle on the the jumpscripts execution model yet.

**Comment by muhamadazmy** [comment]
Closed for the favor of this task: https://github.com/Jumpscale/agent2/issues/38

Full client documentation here:
http://gig.gitbooks.io/jumpscale/content/MultiNode/AgentController2/Python%20Client.html
