### ISSUE TITLE
agentcontroller 2, how can I get to the logs & how to get status of running cmd?

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core7#133]
I can fetch jobs (question: where is this info stored?)
but not the logs on the agents

I should be able to get to all levels as defined in specs once

there should be a way to see which processes are running and then from there see the logs
I found how to see the processes but not how to get to log info

**Comment by muhamadazmy** [comment]
This all is already implemented and already the agentcontroller 2 jobs macro in portal uses this to view the jobs, results and logs. This is done as following:

1- the client.get_jobs() returns the jobs queue history, each job has a list of results (because a single job can run on multiple agents -like in case `fanout`=True)

to retrieve the `logs` you need to query the agent that returned a specific result object for that execution logs.

```python
client = j.clients.ac.getByInstance('main')
job = client.get_jobs()[0] # as an example, get last job
result = job['result'][0] # get reference to first result object (can be the only one)
#get cmd reference.
ref = client.get_by_id(result['gid'], result['nid'], job['id']) 
#Note: command ref abstract access to all execution information of this specific job on this specific agent .. again, this is done because a single job can run on multiple agents.

logs = ref.get_msgs()
#get_msgs, also accepts 'levels' as per specs. default to '*' 

#ref also has other useful methods but only usable with a job in the RUNNING state like `get_stats` which will return the current cpu, and mem consumption of that job. also a `kill` method to stop the execution.
```

Also the client has the `get_processes` method which return the current `RUNNING` jobs on the agent at the moment of the call.

**Comment by muhamadazmy** [comment]
I will update the gitbook with full client documentation

**Comment by muhamadazmy** [comment]
http://gig.gitbooks.io/jumpscale/content/MultiNode/AgentController2/Python%20Client.html
