### ISSUE TITLE
jsdocker does not work

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core7#135]
```
Install jumpscale7 on python 2
[localhost:9022] run: cd /opt/code/github/jumpscale/jumpscale_core7/install/ && bash install.sh
[localhost:9022] out: /bin/bash: line 0: cd: /opt/code/github/jumpscale/jumpscale_core7/install/: No such file or directory
[localhost:9022] out: 


Fatal error: run() received nonzero return code 1 while executing!

Requested: cd /opt/code/github/jumpscale/jumpscale_core7/install/ && bash install.sh
Executed: /bin/bash -l -c "cd /opt/code/github/jumpscale/jumpscale_core7/install/ && bash install.sh"
```

looks like the /opt/code is not mounted

**Comment by despiegk** [comment]
I found the reason
there is new option -s which mounts the /opt/code
THIS NEEDS TO BE THE DEFAULT PLEASE
behaviour was changed
otherwise the -j would not work anyhow

**Comment by muhamadazmy** [comment]
This was changed based on our conversation here  https://youtrack.incubaid.com/issue/devgig-481

Shouldn't we use the new ubuntu images we created instead of the `mc` image? 
Mounting /opt/code is dangerous and will break things when you start shipping dockers to other hosts.
If you started a docker with it's /opt/code mounted, then installed some apps the you committed your changes and exported the image. the exported image will NOT have the installed binaries on it's /opt/code and if you shipped it to another machine it simply won't work. 
Are you sure you still need this to be a default option?

**Comment by despiegk** [comment]
the main usecase for us for using docker is or installed on a pmachine for production & then its using local /opt/code or more important its for testing, which is main usecase

**Comment by despiegk** [comment]
it should work in both modes & it doesn't
when using with jumpscale it should simply work

**Comment by muhamadazmy** [comment]
Fixed, it now mounts /opt/code to the docker container by default, unless `--no-sharecode` is provided
