### ISSUE TITLE
test docker support

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_core7#62]
test/fix instructions on

https://github.com/Jumpscale/play7/tree/master/kvm_docker

improve doc where required

this should be good test of docker/kvm support in jumpscale
& clear instructions for people how to use this

**Comment by muhamadazmy** [comment]
1- Had to move jinja2 from web_python to python base. it's required by kvm package.

**Comment by muhamadazmy** [comment]
2- Updated the do.py script to use ays and to use docker tools for container creation.

**Comment by muhamadazmy** [comment]
@despiegk 
I can see this repo was created: https://github.com/Jumpscale/dockers . is this related to this task? what are the future plans for docker so I can make sure it's consistent and that we have all the functionality to implement it.

**Comment by muhamadazmy** [comment]
I added this [How To Use docker](http://gig.gitbooks.io/jumpscale/content/Howto/How%20To%20Use%20Docker.html) here which runs docker containers using both command line and `jumpscale` extensions. The tests was run on KVM guest machine, just to make sure there is no issue with running docker on kvm.

But using jumpscale to start a kvm machine should be in a separate document (IMHO), since both docker and KVM are not related features of the framework. This is why `kvm` wasn't mentioned in this document.
